[package]
name = "solver"
version = "0.1.0"
edition = "2021"
authors = ["tnagyzambo"]

[dependencies]
anyhow = "1.0.69"
csv = "1.2.0"
nalgebra = {version = "0.32.1", features = ["serde-serialize"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.16" 
rand = "0.8.5"
rand_distr = "0.4.3"
